### PR TITLE
Make it possible to use the plugin with other, GooBook compatible, tools

### PR DESCRIPTION
**Pull request by iamFIREcracker**
This PR add 'g:goobookprg' to let users specify the name of the invoked program

### CODE REVIEW

**Comment by afwlehmann** [comment]
@iamFIREcracker Thanks for the update. Could you update the `README.md` as well?

**Comment by iamFIREcracker** [comment]
You got it.  Let me know if there is anything else you want me to do before the PR is merged.

**Comment by afwlehmann** [comment]
Great job, thanks a lot!

BTW, why not add yourself to the Authors list?

**Comment by iamFIREcracker** [comment]
Since you mentioned it... ;-)

**Comment by afwlehmann** [comment]
:) Thanks once again.

**Pull request merged**
